### PR TITLE
Use correct package as root of dependency graph

### LINKED ISSUE #33: cargo graph does not work with cargo workspaces
When using workspaces, `Cargo.toml`'s `[root]` is basically just backwards compatibility and no longer points to master crate. This makes graph incomplete, cause it doesn't contain all crates from the workspace.

Full description of an issue can be found here: https://github.com/rust-lang/cargo/issues/3203

### PR DESCRIPTION
**Pull request by remram44**
Fixes #33

### CODE REVIEW

**Comment by remram44** [comment]
Some other fixes are included, since the project didn't build with `--features debug` (4c5e60d), and there were some issues with the debug output (e955ce2, 0f35e13).

**Comment by remram44** [comment]
Updated my fix for https://github.com/rust-lang/cargo/pull/4571. `Cargo.toml` files created from current cargo make cargo-graph fail with `error: No root table found for toml file`.

**Comment by kbknapp** [comment]
sorry for missing this! My work schedule has been nuts the last few months and I haven't had time to keep up with these subcommands. Could you rebase on the latest master and this shouod be good for a merge.

**Comment by remram44** [comment]
Sure thing! Rebased without conflict. Note that a `cargo update` might be required to build on current nightly, `rustc-serialize 0.3.18` fails to build.

**Comment by kbknapp** [comment]
thanks! If the latest `rustc-serialize` isn't breaking and builds on stable-2 I don't mind just rolling that up into this PR

**Comment by kbknapp** [comment]
I'm on mobile right now though and can't test if that's the case

**Comment by remram44** [comment]
No problem, committed a cargo update. Builds on stable (1.21) and nightly. Thanks!

**Comment by kbknapp** [comment]
Thanks!

**Pull request merged**
