### PR TITLE
Fix remove orphans

### PR DESCRIPTION
**Pull request by Vaelden**
I investigated #24 and I found 2 problems:

* When an orphan node was detected and removed, the indexes in the nodes vector changed for all the nodes after it, but the edges were not updated to match new indexes. It then triggered an out-of-bound panic on the next loop execution. Also, edges originating from the removed node were not removed.
* The preliminary bound check was incorrect and did not remove edges pointing at/originating from 1-past the number of nodes, resulting in an out-of-bound panic in the next loop.

### CODE REVIEW

**Comment by kbknapp** [comment]
thanks for this fix! :+1: 

@homu r+

**Comment by amarant** [comment]
Could you publish a new version with that change, because I have the same problem with installing from cargo-extras ?
Thanks.

**Comment by kbknapp** [comment]
Ah yeah, sorry!

**Comment by kbknapp** [comment]
@amarant v0.2.1 is out on crates.io

**Pull request merged**
